development:
  adapter: postgresql
  encoding: unicode
  database: twitter_client_development
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: twitter_client_test
  host: localhost